export const INDUSTRIES = [
  "Front-end development",
  "Back-end development",
  "Full-stack development",
  "Mobile app development",
  "Web development",
  "Game development",
  "Artificial intelligence/machine learning",
  "Data science",
  "Database administration",
  "Cloud computing",
  "Cybersecurity",
  "DevOps",
  "Project management",
  "Quality assurance/testing",
  "Network administration",
  "Systems administration",
  "UI/UX design",
  "Graphic design",
  "Technical writing",
  "Content creation",
  "Digital marketing",
  "Social media management",
  "E-commerce",
  "Business intelligence",
  "Big data analytics",
  "Embedded systems",
  "Internet of things (IoT)",
  "Virtual reality (VR)",
  "Augmented reality (AR)",
  "Natural language processing (NLP)",
  "Robotics",
  "Computer vision",
  "Cloud architecture",
  "Cloud infrastructure",
  "Cloud development",
  "Cloud security",
  "Software engineering",
  "Machine learning engineering",
  "Data engineering",
  "Data analysis",
  "Data visualization",
  "Data warehousing",
  "Distributed systems",
  "High-performance computing",
  "Quantum computing",
  "Blockchain development",
  "Cryptocurrency development",
  "Game design",
  "Video production/editing",
  "Audio production/editing",
];
