export const TOPICS = [
  "HTML5",
  "CSS3",
  "JavaScript",
  "React",
  "Vue",
  "Angular",
  "TypeScript",
  "Bootstrap",
  "Responsive Web Design",
  "Accessibility",
  "Cross-Browser Compatibility",
  "Performance Optimization",
  "User Interface (UI) Design",
  "User Experience (UX) Design",
  "Progressive Web Apps (PWAs)",
  "Front End Frameworks",
  "Front End Libraries",
  "Front End Build Tools",
  "Version Control (e.g., Git)",
  "Front End Testing (e.g., Jest, Enzyme)",
  "Front End Security",
  "Front End Performance Monitoring",
  "Code Optimization",
  "Front End Debugging",
  "Web Accessibility Guidelines (e.g., WCAG)",
  "Single Page Applications (SPAs)",
  "Responsive Images",
  "Web Components",
  "Front End Performance Auditing",
  "Performance Metrics (e.g., Lighthouse, WebPageTest)",
  "SEO Best Practices",
  "Animation and Transitions",
  "Progressive Enhancement",
  "Feature Detection",
  "Media Queries",
  "Grid Layout",
  "Flexbox",
  "Server-Side Rendering (SSR)",
  "Client-Side Rendering (CSR)",
  "Server Push",
  "Code Splitting",
  "Lazy Loading",
  "Web Performance Optimization (WPO)",
  "Design Patterns for Front End Development",
  "Web Accessibility Evaluation Tools",
  "Front End Development Workflow",
  "Front End Design Systems",
  "Mobile-First Development",
  "Front End Performance Optimization Techniques",
];
